version: '3'
services:
  app:
    build: .
    container_name: face-recog-container
    command: uvicorn app.main:app --host 0.0.0.0 --port 7979
    ports:
      - 7979:7979
    volumes:
      - type: volume
        source: img_db
        target: /app/app/data
volumes:
  img_db:
